AWSTemplateFormatVersion: "2010-09-09"

Description: "Phase List Static S3 Website"

Parameters:
  PhaseListBucketName:
    Type: String
    Description: Name of the bucket
    Default: phaselist

Resources:

#  PhaseListDailyRule:
#    Type: "AWS::Events::Rule"
#    Properties:
#      Description: "Schedule for running the PhaseList Lambda function"
#      Name: PhaseListScheduleRule
#      ScheduleExpression: "cron(0 10 * * ? *)"
#      State: Enabled
#      Targets:
#        - Ref: PhaseListLambda

  LogGroup: 
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 5

  PhaseListRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal: 
              Service: 
                - "s3.amazonaws.com"
              Service:
                - "lambda.amazonaws.com"
            Action:
              -  "sts:AssumeRole"
      Path: "/"
      RoleName: {"Fn::Join": ["", [{"Ref": "AWS::Region"}, {"Ref": "PhaseListBucketName"}]]}

  PhaseListLambdaExecutionPolicy:
    DependsOn: PhaseListRole
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: PhaseListUpdateHTMLRolePolicy
      Roles: 
        - 
          !Ref "PhaseListRole"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: 
              - "s3:PutObject"
            Resource:
              Fn::Join:
                - ""
                -
                  - "arn:aws:s3:::"
                  -
                    Ref: PhaseListBucketName
                  - "/*"

  PhaseListLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: "Test Lambda Function"
      FunctionName: PhaseList
      Handler: index.my_handler
      MemorySize: 128
      Role: !GetAtt PhaseListRole.Arn 
      Runtime: python2.7
      Code:
        ZipFile: lambda/lambda.zip

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref PhaseListBucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: phaselist.html
        ErrorDocument: error.html
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: 
        Ref: PhaseListBucketName
      PolicyDocument: 
        Statement:
          -
            Sid: "PublicReadGetObject"
            Effect: "Allow"
            Principal: "*"
            Action:
              - "s3:GetObject"
            Resource:
              Fn::Join:
                - ""
                -
                  - "arn:aws:s3:::"
                  -
                    Ref: PhaseListBucketName
                  - "/*"

Outputs:
  WebsiteURL:
    Value: !GetAtt S3Bucket.WebsiteURL
    Description: phaselist website hosted on S3
  S3BucketSecureURL:
    Value: !Sub
        - https://${Domain}
        - Domain: !GetAtt S3Bucket.DomainName
    Description: phaselist

