steps:
  - plugins:
      - shellcheck#v1.1.2:
          files: scripts/*.sh

  - command: "docker build -t pkumaschow/phaselist ."
    label: "build docker image"

  - wait

  - command: "scripts/makepage.sh"
    label: "test docker image"

  - wait

  - command: "scripts/publish.sh"
    label: "push to docker hub"
